Repository AndreaBozzo/Osservatorio, pull requests merged in 2025-07, with the labels that each got.

#23 Day 3: DuckDB Performance Testing & Optimization Complete
  .claude/settings.local.json
  CHANGELOG.md
  README.md
  SECURITY.md
  data/performance_baselines.json
  docs/README.md
  docs/REORGANIZATION_SUMMARY.md
  docs/adr/001-database-selection.md
  docs/api/API_REFERENCE.md
  docs/architecture/ARCHITECTURE.md
  docs/github/ISSUE_TEMPLATES.md
  docs/guides/PERFORMANCE_TESTING.md
  docs/project/CLAUDE.md
  docs/project/PROJECT_STATE.md
  docs/project/REPOSITORY_CLEANUP_SUMMARY.md
  examples/duckdb_query_builder_demo.py
  pytest.ini
  scripts/README.md
  scripts/performance_regression_detector.py
  src/database/duckdb/__init__.py
  src/database/duckdb/config.py
  src/database/duckdb/manager.py
  src/database/duckdb/partitioning.py
  src/database/duckdb/query_builder.py
  src/database/duckdb/query_optimizer.py
  src/database/duckdb/schema.py
  src/database/duckdb/simple_adapter.py
  tests/performance/test_duckdb_performance.py
  tests/performance/test_query_builder_performance.py
  tests/performance/test_scalability.py
  tests/unit/test_duckdb_query_builder.py
Labels: status: ready, component: database, breaking change

#35 Day 4: SQLite Metadata Layer Implementation & Comprehensive Documentation
  CHANGELOG.md
  README.md
  docs/core/API_REFERENCE.md
  docs/core/ARCHITECTURE.md
  docs/core/PERFORMANCE.md
  docs/project/CLAUDE.md
  docs/project/PROJECT_STATE.md
  examples/sqlite_metadata_demo.py
  src/database/__init__.py
  src/database/duckdb/manager.py
  src/database/sqlite/__init__.py
  src/database/sqlite/manager.py
  src/database/sqlite/repository.py
  src/database/sqlite/schema.py
  src/utils/security_enhanced.py
  tests/integration/test_unified_repository.py
  tests/performance/test_duckdb_performance.py
  tests/unit/test_sqlite_metadata.py
  tests/utils/__init__.py
  tests/utils/database_cleanup.py
Labels: type: feature, priority: critical, effort: hours, component: database

#36 Updates for dashboard/index.html
  dashboard/index.html
Labels: enhancement, type: documentation, priority: low, effort: hours

#49 Day 6: PowerBI Enterprise Integration Enhancement
  .gitignore
  Makefile
  README.md
  convert_to_powerbi.py
  convert_to_tableau.py
  data/performance_baselines.json
  docs/core/API_REFERENCE.md
  docs/core/ARCHITECTURE.md
  docs/integrations/POWERBI_INTEGRATION.md
  docs/project/CLAUDE.md
  docs/project/PROJECT_STATE.md
  examples/powerbi_integration_demo.py
  pytest.ini
  scripts/validate_powerbi_offline.py
  src/database/sqlite/manager.py
  src/database/sqlite/repository.py
  src/database/sqlite/schema.py
  src/integrations/__init__.py
  src/integrations/powerbi/__init__.py
  src/integrations/powerbi/incremental.py
  src/integrations/powerbi/metadata_bridge.py
  src/integrations/powerbi/optimizer.py
  src/integrations/powerbi/templates.py
  templates/powerbi/demo_popolazione_template.pbit
  tests/integration/test_powerbi_integration.py
  tests/unit/test_powerbi_api.py
  tests/unit/test_sqlite_metadata.py
Labels: documentation, type: feature, status: ready, component: dashboard

#55 added check for special char count
  src/api/istat_api.py
Labels: type: feature, priority: high, status: ready, component: etl
